import { env } from './env';

export const config = {
  port: env.PORT,
  databaseUrl: env.DATABASE_URL,
  redisUrl: env.REDIS_URL,
  jwtSecret: env.JWT_SECRET,
  env: env.NODE_ENV,
  encryptionSecret: env.ENCRYPTION_SECRET,
  frontendUrl: env.FRONTEND_URL,
  appBaseUrl: env.APP_BASE_URL,
  storagePath: env.STORAGE_PATH,
  internalJobSecret: env.INTERNAL_JOB_SECRET,
  whatsappLogRetentionDays: env.WHATSAPP_LOG_RETENTION_DAYS,
  auditLogRetentionDays: env.AUDIT_LOG_RETENTION_DAYS,
  google: {
    clientId: env.GOOGLE_CLIENT_ID,
    clientSecret: env.GOOGLE_CLIENT_SECRET,
    redirectUri: env.GOOGLE_OAUTH_REDIRECT_URI || `${env.APP_BASE_URL}/api/calendar/oauth/GOOGLE/callback`,
  },
  microsoft: {
    clientId: env.MICROSOFT_CLIENT_ID,
    clientSecret: env.MICROSOFT_CLIENT_SECRET,
    redirectUri: env.MICROSOFT_OAUTH_REDIRECT_URI || `${env.APP_BASE_URL}/api/calendar/oauth/MICROSOFT/callback`,
  },
  notificationEngine: {
    enabled: env.NOTIFICATION_ENGINE_ENABLED,
    escalationEnabled: env.NOTIFICATION_ESCALATION_ENABLED,
    quietHoursEnabled: env.NOTIFICATION_QUIET_HOURS_ENABLED,
    channelFallbackEnabled: env.NOTIFICATION_CHANNEL_FALLBACK_ENABLED,
    policyBuilderEnabled: env.NOTIFICATION_POLICY_BUILDER_ENABLED,
    maxRetries: env.NOTIFICATION_MAX_RETRIES,
    retryBaseDelaySeconds: env.NOTIFICATION_RETRY_BASE_DELAY_SECONDS,
    retryMaxDelayMinutes: env.NOTIFICATION_RETRY_MAX_DELAY_MINUTES,
    recipientMaxPerHour: env.NOTIFICATION_RECIPIENT_MAX_PER_HOUR,
    eventCooldownMinutes: env.NOTIFICATION_EVENT_COOLDOWN_MINUTES,
    deliveryRetentionDays: env.NOTIFICATION_DELIVERY_RETENTION_DAYS,
  },
  smtp: {
    host: env.SMTP_HOST,
    port: env.SMTP_PORT,
    secure: env.SMTP_SECURE,
    user: env.SMTP_USER,
    password: env.SMTP_PASSWORD,
    from: env.SMTP_FROM || 'no-reply@presencaflow.com',
  },
};
